package.json
src/index.js

Adding policy projection export

OMT-249 contributions

---

src/components/FamilyOrInsureePoliciesSummary.js

TICKET: [OTC-732](https://openimis.atlassian.net/browse/OTC-732)

OTC-732: Fixed check for confirmed action

---

src/actions.js
src/components/PolicyFilter.js
src/components/PolicyForm.js
src/components/PolicyMasterPanel.js
src/pages/PolicyPage.js

https://openimis.atlassian.net/browse/OP-1014

OP-1014: modular IMIS: renewing of free enrolment policies doesn't work

---

src/components/InsureeEligibilitySummary.js

Ticket:
https://openimis.atlassian.net/browse/OP-1060
Changes:
- added componentDidMount
- simplified componentDidUpdate
I'm not sure if I can get rid off componentDidUpdate since I couldn't find answer if it is needed in others component
Related PR:
https://github.com/openimis/openimis-fe-policy_js/pull/24

Feature/op 1060: added displaying for missing table of data in enquiry

---

src/index.js

Part of [CORE PR](https://github.com/openimis/openimis-fe-core_js/pull/88)
Part of [CONTRIBUTION PR](https://github.com/openimis/openimis-fe-contribution_js/pull/7)
In scope of this PR, I expanded the policy projection by adding code property.

OP-1037: Fetching products code

---

src/actions.js
src/components/InsureeItemEligibility.js

https://openimis.atlassian.net/browse/OTC-780
This PR fixes displaying a Thumb icon. 
Here is the backend part: https://github.com/openimis/openimis-be-policy_py/pull/39

OTC-780: fix Thumb icon

---

src/components/PolicyMasterPanel.js
src/pickers/PolicyOfficerPicker.js

https://openimis.atlassian.net/browse/OTC-799

OTC-799: modular IMIS:  it is possible to create a policy with an enrolment officer who has the family noit in his/her catchments area.

---

src/components/PolicyForm.js
src/components/PolicyMasterPanel.js

[OTC-937](https://openimis.atlassian.net/browse/OTC-937)
Changes:
- I added optional chaining where it was recommended.
- I changed the condition and I'm invoking _decodeId_ only if family exists.
[OTC-937]: https://openimis.atlassian.net/browse/OTC-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-937: enabling assignment of the policy to a family

---

src/pages/PolicyPage.js

https://openimis.atlassian.net/browse/OTC-916
It also a part of this PR: https://github.com/openimis/openimis-fe-insuree_js/pull/42

OTC-916: add key to a component so it would reload when key changes

---

src/components/InsureeEligibilitySummary.js

https://openimis.atlassian.net/browse/OTC-935
After merging this PR the data will be shown as number or N/A which means not available.

OTC-938: update displaying data in eligibility summary

---

src/components/PolicyValuesPanel.js

Policy values panel in Policy page is set to readonly
https://openimis.atlassian.net/browse/OTC-867

OTC-867: modular IMIS: contribution form doesn't show how much it should be paid yet

---

src/actions.js
src/components/FamilyOrInsureePoliciesSummary.js
src/components/InsureeEligibilityEnquiry.js
src/components/PolicyFilter.js
src/components/PolicySearcher.js

[OP-1084](https://openimis.atlassian.net/browse/OP-1084)
Changes:
- Pagination fix in **_PolicySearcher.js_**. **Last** and **first** parameters had to be adjusted to the existing logic.
- Removal of redundant imports which were causing warnings in console.
[OP-1084]: https://openimis.atlassian.net/browse/OP-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1084: Pagination fix in PolicySearcher.js

---

src/components/PolicyMasterPanel.js
src/components/PolicyValuesPanel.js

Ticket: https://openimis.atlassian.net/browse/OP-1306
Changes:
- Removed redundant console.log
- Fixed fetching product assigned to district.

OP-1306: Fixed product from district in policy.

---

src/components/PolicyFilter.js
src/translations/en.json

[OP-1397](https://openimis.atlassian.net/browse/OP-1397)
Changes:
- Added missing labels as well as placeholders.
- New keys have been added to the Lokalise.
[OP-1397]: https://openimis.atlassian.net/browse/OP-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1397: Restoring missing labels in Product and PolicyOfficer pickers

---

src/actions.js
src/components/InsureeItemEligibility.js
src/components/InsureeServiceEligibility.js
src/components/PolicyFilter.js
src/components/PolicyMasterPanel.js
src/components/PolicyValuesPanel.js
src/pages/PoliciesPage.js
src/pickers/PolicyOfficerPicker.js
src/reducer.js
src/translations/en.json

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

src/components/PolicyFilter.js

[OTC-1095](https://openimis.atlassian.net/browse/OTC-1095)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
- I got rid of the local state and implemented enhanced logic to handle checkbox buttons.
[OTC-1095]: https://openimis.atlassian.net/browse/OTC-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-1095: fix reseting search criterias in policy module

---

src/actions.js
src/components/PolicyForm.js

https://openimis.atlassian.net/browse/OTC-800
Fixed the issue when selecting an officer start date of the policy becomes null.

OTC-800: modular IMIS: renewing of free enrolment policies doesn't work

---

src/components/InsureePolicyEligibilitySummary.js

https://openimis.atlassian.net/browse/OP-1496
This PR will allow to fetch policies valid at given time.
Related to:
https://github.com/openimis/openimis-fe-claim_js/pull/129

OP-1496: allow to query policies with target_date

---

src/index.js

[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
[RELATED PR #1](https://github.com/openimis/openimis-fe-insuree_js/pull/90)
[RELATED PR #2 ](https://github.com/openimis/openimis-fe-claim_js/pull/148)
Changes:
- Add new contribution point to display policies of provided insuree.
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-95: create new contribution point

---

src/components/FamilyOrInsureePoliciesSummary.js

[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
Changes:
- Add possiblity to hide add button in policy section. 
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-95: add possibility to hide add button in policy block

---

README.md
src/components/PolicyMasterPanel.js

Ticket: https://openimis.atlassian.net/browse/ONI-9
Changes:
- Added setting to limit effective date of a policy.
- Default is 0 days - it means nothing has changed.
- Nepal requested 90 days.

ONI-9: Added setting to limit effective date of a policy.

---

README.md
src/components/FamilyOrInsureePoliciesSummary.js
src/components/InsureeEligibilitySummary.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/ONI-18
Changes:
- Added setting to enable/disable counts/amounts in enquire. Default enabled.
- Added enrolment date to policies.

ONI-18: Hide remain counts on setting. Display enrolment date in policies.

---

src/components/PolicyFilter.js

Ticket: https://openimis.atlassian.net/browse/ONI-39
BE: https://github.com/openimis/openimis-be-policy_py/pull/80
Changes:
- Added filter for confirmation type of family connected to policy

ONI-39: Added contribution type filter.

---

src/index.js

[OP-1617](https://openimis.atlassian.net/browse/OP-1617)
[REQUIRED PR](https://github.com/openimis/openimis-fe-contribution_js/pull/33)
Changes:
- Expand policy projection by adding sumPremiums field.
[OP-1617]: https://openimis.atlassian.net/browse/OP-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1617: expand policy projection

---

src/index.js

[OP-1619](https://openimis.atlassian.net/browse/OP-1619)
[CONTRIBUTION REQUIRED PR](https://github.com/openimis/openimis-fe-contribution_js/pull/35)
[CORE REQUIRED PR](https://github.com/openimis/openimis-fe-core_js/pull/182)
Changes:
- Add policy projection extended by family details.
[OP-1619]: https://openimis.atlassian.net/browse/OP-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1619: implement policy projection with family details fields

---

src/components/PolicyFilter.js
src/components/PolicyMasterPanel.js

MERGING develop into release/23.10

MERGING develop into release/23.10

---

src/components/PolicyMasterPanel.js

Ticket: https://openimis.atlassian.net/browse/OP-1791
Changes:
- Added maximum date validation for enrol date of policy - no dates in the future.

OP-1791: Added maximum date to policy enrolment date.

---

src/components/FamilyOrInsureePoliciesSummary.js

[OP-1822](https://openimis.atlassian.net/browse/OP-1822)
[RELATED](https://github.com/openimis/openimis-fe-insuree_js/pull/127)
Changes:
- Add possibility to disable policy selection.
[OP-1822]: https://openimis.atlassian.net/browse/OP-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1822: add possibility to disable policy selection
